In [1]:
from FNN import FNN
from Layer import Layer
from Neuron import Neuron
import numpy as np
from ActivFunctions import  *
from InitFunctions import  *
from SuppFunctions import  *

Neuron Class functionality testing

In [2]:
inputTest = np.array([1.0,1.0])

In [3]:
#zero initialization
t0NeuronZero = Neuron(2,identity)
print(t0NeuronZero.weight_vector.shape)
t0NeuronZero.forward(inputTest)

(1, 3)


[array([[0.]]), array([[0.]])]

In [4]:
#random initialization
t0NeuronRandom = Neuron(2,identity,method_ini="Random")
print(t0NeuronRandom.weight_vector.shape)
t0NeuronRandom.forward(inputTest)

(1, 3)


[array([[2.50404887]]), array([[2.50404887]])]

In [5]:
#initialization from vector
vector = np.array([1.0,2.0,3.5])
print(vector)
print(vector.shape)
t1Neuron = Neuron(vector,identity)
print(t1Neuron.weight_vector.shape)
t1Neuron.forward(inputTest)

[1.  2.  3.5]
(3,)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [6]:
#initialization from row vector(2D array)
vector_row = vector[np.newaxis,:]
print(vector_row)
print(vector_row.shape)
t2Neuron = Neuron(vector_row,identity)
print(t2Neuron.weight_vector.shape)
t2Neuron.forward(inputTest)

[[1.  2.  3.5]]
(1, 3)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [7]:
#initialization from column vector(2D array)
vector_column = vector[:,np.newaxis]
print(vector_column)
print(vector_column.shape)
t3Neuron = Neuron(vector_column,identity)
print(t3Neuron.weight_vector.shape)
t3Neuron.forward(inputTest)

[[1. ]
 [2. ]
 [3.5]]
(3, 1)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [8]:
#array input
t0NeuronRandom = Neuron(2,identity,method_ini="Random")
inputTest = np.array([[1.0,1.0],[1.0,1.0]])
print(inputTest.shape)
print(inputTest)
print(t0NeuronRandom.weight_vector.shape)
t0NeuronRandom.forward(inputTest)

(2, 2)
[[1. 1.]
 [1. 1.]]
(1, 3)


[array([[1.71915906, 1.71915906]]), array([[1.71915906, 1.71915906]])]

In [9]:
#wrong activ function
vector = np.array([1.0,2.0,3.5])
errorNeuron = Neuron(vector,1)

NotImplementedError: 

In [ ]:
#wrong input function
vector = np.array(["1.0","2.0","3.5"])
errorNeuron = Neuron(vector,identity)

NotImplementedError: 

In [ ]:
#wrong input (too small)
vector = np.array([1.0,2.0,3.5])
neuronTest = Neuron(vector,identity)
inputTestErrorSmall = np.array([1.0])
neuronTest.forward(inputTestErrorSmall)

NotImplementedError: 

In [ ]:
#wrong input (too big)
vector = np.array([1.0,2.0,3.5])
neuronTest = Neuron(vector,identity)
inputTestErrorBig = np.array([[1.0],[1.0],[1.0],[1.0]])
print(inputTestErrorBig)
neuronTest.forward(inputTestErrorBig)

[[1.]
 [1.]
 [1.]
 [1.]]


NotImplementedError: 

Layer class implementation testing

In [10]:
#initialization by number of dim in vector
dim_layer = np.array([4,5])
testLayer = Layer(dim_layer,identity,method_ini="Random")
testLayer.weight_array
testLayer.activ_functions

[<function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>]

In [ ]:
#forward test pass
inputTestVect = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])

print(testLayer.forward(inputTestVect))
print(testLayer.forward(inputTestArray))

[array([[3.2923666 ],
       [3.083872  ],
       [3.98799396],
       [1.64653793]]), array([[3.2923666 ],
       [3.083872  ],
       [3.98799396],
       [1.64653793]])]
[array([[3.2923666 , 6.40332792],
       [3.083872  , 5.74255898],
       [3.98799396, 7.54800514],
       [1.64653793, 2.96671661]]), array([[3.2923666 , 6.40332792],
       [3.083872  , 5.74255898],
       [3.98799396, 7.54800514],
       [1.64653793, 2.96671661]])]


FNN class implementation testing

In [ ]:
#initialization by number of dim in vector
dim_layer = np.array([4,5,3])
testLayer = Layer(dim_layer,identity,method_ini="Random")
testLayer.weight_array
testLayer.activ_functions