In [22]:
from FNN import FNN
from Layer import Layer
from Neuron import Neuron
import numpy as np
from ActivFunctions import  *
from InitFunctions import  *
from SuppFunctions import  *
from ErrorClasses import *

Neuron Class functionality testing

In [23]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#zero initialization
neuron = Neuron(2,identity)
print(neuron.weight_vector.shape)
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

(1, 3)
[array([[0.]]), array([[0.]])]
[array([[0.]]), array([[0.]])]
[array([[0.]]), array([[0.]])]
[array([[0.]]), array([[0.]])]
[array([[0., 0.]]), array([[0., 0.]])]


In [24]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#random initialization
neuron = Neuron(2,identity,method_ini="Random")
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

[array([[0.96322682]]), array([[0.96322682]])]
[array([[0.96322682]]), array([[0.96322682]])]
[array([[0.96322682]]), array([[0.96322682]])]
[array([[0.96322682]]), array([[0.96322682]])]
[array([[0.96322682, 1.68628508]]), array([[0.96322682, 1.68628508]])]


In [25]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#initialization from list
vector = [1.0,2.0,3.5]
neuron = Neuron(vector,identity)
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[ 6.5, 12. ]]), array([[ 6.5, 12. ]])]


In [26]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#initialization from vector
vector = np.array([1.0,2.0,3.5])
neuron = Neuron(vector,identity)
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[ 6.5, 12. ]]), array([[ 6.5, 12. ]])]


In [27]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#initialization from row vector(2D array)
vector = np.array([1.0,2.0,3.5])
vector_row = vector[np.newaxis,:]
neuron = Neuron(vector_row,identity)
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[ 6.5, 12. ]]), array([[ 6.5, 12. ]])]


In [28]:
#inputs
inputTestList = [1.0,1.0]
inputTestVect1D = np.array([1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0]])
#initialization from column vector(2D array)
vector = np.array([1.0,2.0,3.5])
vector_column = vector[:,np.newaxis]
neuron = Neuron(vector_column,identity)
#forward pass
print(neuron.forward(inputTestList))
print(neuron.forward(inputTestVect1D))
print(neuron.forward(inputTestVect2Drow))
print(neuron.forward(inputTestVect2Dcol))
print(neuron.forward(inputTestArray))

[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[6.5]]), array([[6.5]])]
[array([[ 6.5, 12. ]]), array([[ 6.5, 12. ]])]


In [29]:
#error messages testing
print("Test for: no function given as activation function")
try:
    vector = np.array([1.0,2.0,3.5])
    errorNeuron = Neuron(vector,1)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not vector given for weights initialization (2 dim)")
try:
    vector = np.array([[1.0,2.0,3.5],[1.0,2.0,3.5]])
    errorNeuron = Neuron(vector,identity)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not vector given for weights initialization (higher than 2 dim)")
try:
    vector = np.array([[[1.0,2.0,3.5],[1.0,2.0,3.5]],[[1.0,2.0,3.5],[1.0,2.0,3.5]]])
    errorNeuron = Neuron(vector,identity)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong weights given for initialization")
try:
    vector = np.array(["1.0","2.0","3.5"])
    errorNeuron = Neuron(vector,identity)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong var type given in list for weight initialization")
try:
    vector = ["as","2.0","3.5"]
    errorNeuron = Neuron(vector,identity)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - inproper dimension of input")
try:
    vector = np.array([1.0,2.0,3.5])
    t0NeuronRandom = Neuron(vector,identity,method_ini="Random")
    inputTest = np.array([[[1.0,1.0],[1.0,1.0]],[[1.0,1.0],[1.0,1.0]]]) 
    t0NeuronRandom.forward(inputTest)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedArrayDimGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - wrong value types in input: they are not rational numbers")
try:
    vector = np.array([1.0,2.0,3.5])
    t0NeuronRandom = Neuron(vector,identity,method_ini="Random")
    inputTest = np.array([1.0 + 3j,1.0]) 
    t0NeuronRandom.forward(inputTest)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - given variable is of not supported type for list")
try:
    vector = np.array([1.0,2.0,3.5])
    t0NeuronRandom = Neuron(vector,identity,method_ini="Random")
    inputTest = ["a","1.0"]
    t0NeuronRandom.forward(inputTest)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - given variable is of not supported type")
try:
    vector = np.array([1.0,2.0,3.5])
    t0NeuronRandom = Neuron(vector,identity,method_ini="Random")
    inputTest = "a"
    t0NeuronRandom.forward(inputTest)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - given input is too small to match neuron dimensions")
try:
    #wrong input (too small)
    vector = np.array([1.0,2.0,3.5])
    neuronTest = Neuron(vector,identity)
    inputTestErrorSmall = np.array([1.0])
    neuronTest.forward(inputTestErrorSmall)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation (forward pass) - given input is too small to match neuron dimensions")
try:
    #wrong input (too big)
    vector = np.array([1.0,2.0,3.5])
    neuronTest = Neuron(vector,identity)
    inputTestErrorBig = np.array([[1.0],[1.0],[1.0],[1.0]])
    neuronTest.forward(inputTestErrorBig)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")

Test for: no function given as activation function
Correct errors was caught. Error: Given input is not supported by implementation for activation function initialization. Given variable is not a function and thus can not be used as activation function.
Test for: not vector given for weights initialization (2 dim)
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization. Given variable is not an vector (not column or row vector in 2 dim), so it is unsuitable for neuron weight initialization.
Test for: not vector given for weights initialization (higher than 2 dim)
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization. Given variable is not an vector (due to more than 2 dim), so it is unsuitable for neuron weight initialization.
Test for: wrong weights given for initialization
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization.

Layer class implementation testing

In [ ]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by number of dim in vector
dim_layer = np.array([4,5])
testLayer = Layer(dim_layer,identity,method_ini="Random")
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[[ 0.43321761 -0.39133967  0.02218713  0.0313213   0.6934288   0.30996487]
 [-0.11152912 -0.70523287 -0.77345744 -0.20196702  0.1988356   0.65243125]
 [ 0.80787798 -0.73697185 -0.77146234 -0.53531642 -0.53482409 -0.25597751]
 [-0.78927112 -0.13352324  0.615267    0.4524414  -0.15706959 -0.27352318]]
[<function identity at 0x0000017F124FA160>, <function identity at 0x0000017F124FA160>, <function identity at 0x0000017F124FA160>, <function identity at 0x0000017F124FA160>]
[array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       [-0.28567874]]), array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       [-0.28567874]])]
[array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       [-0.28567874]]), array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       [-0.28567874]])]
[array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       [-0.28567874]]), array([[ 1.09878005],
       [-0.9409196 ],
       [-2.02667423],
       

In [ ]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by number of dim in list
dim_layer = [4,5]
testLayer = Layer(dim_layer,identity,method_ini="Random")
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[[ 0.8061142  -0.12231126 -0.33229773 -0.60637171  0.08254818  0.35686078]
 [-0.61314214  0.70452086  0.03788413  0.32575421 -0.15947243 -0.02173008]
 [ 0.33347566 -0.44683947  0.57252151  0.22420844 -0.44150839 -0.20875436]
 [-0.65070032  0.78306672 -0.50197369  0.37594698  0.39965875 -0.27763373]]
[<function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>]
[array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]]), array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]])]
[array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]]), array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]])]
[array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]]), array([[0.18454246],
       [0.27381456],
       [0.03310339],
       [0.12836472]])]
[array(

In [ ]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by giving weight array
weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
testLayer = Layer(weights,identity,method_ini="Random")
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[[ 1.  -4.  -4.   3.   3.   3. ]
 [-1.  -4.   3.5  3.5  3.5  3. ]
 [ 2.  -4.  -2.5  3.   2.2  3. ]]
[<function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]]), array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]])]


In [ ]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by giving weight array and function (single) from list
weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
testLayer = Layer(weights,[identity],method_ini="Random")
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[[ 1.  -4.  -4.   3.   3.   3. ]
 [-1.  -4.   3.5  3.5  3.5  3. ]
 [ 2.  -4.  -2.5  3.   2.2  3. ]]
[<function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]]), array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]])]


In [ ]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by giving weight array and identity function (mutliple same) from list
weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
activation_functions = [identity,identity,identity]
testLayer = Layer(weights,activation_functions,method_ini="Random")
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[[ 1.  -4.  -4.   3.   3.   3. ]
 [-1.  -4.   3.5  3.5  3.5  3. ]
 [ 2.  -4.  -2.5  3.   2.2  3. ]]
[<function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[2. ],
       [8.5],
       [3.7]])]
[array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]]), array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]])]


In [45]:
#Input data for input propagation (forward pass)
inputTestList = [1.0,1.0,1.0,1.0,1.0]
inputTestVect1D = np.array([1.0,1.0,1.0,1.0,1.0])
inputTestVect2Drow = np.array([[1.0,1.0,1.0,1.0,1.0]])
inputTestVect2Dcol = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
#initialization by giving weight array and identity function (mutliple different) from list
weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
activation_functions = [sigmoid,relu,leaky_relu]
testLayer = Layer(weights,activation_functions)
#forward pass
print(testLayer.forward(inputTestList))
print(testLayer.forward(inputTestVect1D))
print(testLayer.forward(inputTestVect2Drow))
print(testLayer.forward(inputTestVect2Dcol))
print(testLayer.forward(inputTestArray))

[array([[2. ],
       [8.5],
       [3.7]]), array([[0.88079708],
       [8.5       ],
       [3.7       ]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[0.88079708],
       [8.5       ],
       [3.7       ]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[0.88079708],
       [8.5       ],
       [3.7       ]])]
[array([[2. ],
       [8.5],
       [3.7]]), array([[0.88079708],
       [8.5       ],
       [3.7       ]])]
[array([[ 2. ,  3. ],
       [ 8.5, 18. ],
       [ 3.7,  5.4]]), array([[ 0.88079708,  0.95257413],
       [ 8.5       , 18.        ],
       [ 3.7       ,  5.4       ]])]


In [49]:
#error messages testing
print("Test for: wrong var type (not number) given in list for weight initialization")
try:
    vector = ["as","2.0"]
    testLayer = Layer(vector,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong var type given (number, but no int) in list for weight initialization")
try:
    vector = [1,2.3]
    testLayer = Layer(vector,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong var type (not number) given in 1D array for weight initialization")
try:
    vector = np.array(["as","2.0"])
    testLayer = Layer(vector,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong var type given (number, but no int) in 1D array for weight initialization")
try:
    vector = np.array([1,2.3])
    testLayer = Layer(vector,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: wrong dimensions of given 1D array for weight initialization")
try:
    vector = np.array([1,2,1,1,2])
    testLayer = Layer(vector,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not rational numbers given in 2D array for weight initialization")
try:
    weights = np.array([[1.0 + 4j,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    testLayer = Layer(weights,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not enough information given in 2D array for weight initialization")
try:
    weights = np.array([[]])
    testLayer = Layer(weights,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: bigger than 2D was given for array for weight initialization")
try:
    weights = np.array([[[2]]])
    testLayer = Layer(weights,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedArrayDimGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not supported data type given for array for weight initialization")
try:
    weights = "hehe"
    testLayer = Layer(weights,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not supported data type given for array for weight initialization")
try:
    weights = "hehe"
    testLayer = Layer(weights,identity,method_ini="Random")   
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not compatible amount of activation functions given to the amount of neurons for activation function initialization")
try:
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,relu,leaky_relu,leaky_relu]
    testLayer = Layer(weights,activation_functions)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not activation function given (inside list) for activation function initialization")
try:
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,1,leaky_relu]
    testLayer = Layer(weights,activation_functions)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not activation function given (standalone) for activation function initialization")
try:
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = 1
    testLayer = Layer(weights,activation_functions)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation, too much dimensions in input")
try:
    #Input data for input propagation (forward pass)
    inputTestArray = np.array([[[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]],[[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]]])
    #model ini
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,sigmoid,leaky_relu]
    testLayer = Layer(weights,activation_functions)
    #forward pass test
    testLayer.forward(inputTestArray)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedArrayDimGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation, complex input")
try:
    #Input data for input propagation (forward pass)
    inputTestVect = np.array([[1.0 + 3j],[1.0],[1.0],[1.0],[1.0]])
    #model ini
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,sigmoid,leaky_relu]
    testLayer = Layer(weights,activation_functions)
    #forward pass test
    testLayer.forward(inputTestVect)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation, wrong data type of input")
try:
    #Input data for input propagation (forward pass)
    inputTestVect = "sda"
    #model ini
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,sigmoid,leaky_relu]
    testLayer = Layer(weights,activation_functions)
    #forward pass test
    testLayer.forward(inputTestVect)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation, wrong data type of input in list")
try:
    #Input data for input propagation (forward pass)
    inputTestList =["a",1.0,1.0,1.0,1.0]
    inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])
    #model ini
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,sigmoid,leaky_relu]
    testLayer = Layer(weights,activation_functions)
    #forward pass test
    testLayer.forward(inputTestList)
    testLayer.forward(inputTestArray)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: input propagation, input does not match layer neurons")
try:
    #Input data for input propagation (forward pass)
    inputTestList = [1.0,1.0,1.0,1.0,1.0,1.0,1.0]
    #model ini
    weights = np.array([[1.0,-4.0,-4.0,3.0,3.0,3.0],[-1.0,-4.0,3.5,3.5,3.5,3.0],[2.0,-4.0,-2.5,3.0,2.2,3.0]])
    activation_functions = [sigmoid,sigmoid,leaky_relu]
    testLayer = Layer(weights,activation_functions)
    #forward pass test
    testLayer.forward(inputTestList)
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error:",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")

Test for: wrong var type (not number) given in list for weight initialization
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization. Given values are not integers and thus can not represent of layer weights matrix.
Test for: wrong var type given (number, but no int) in list for weight initialization
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization. Given values are not integers and thus can not represent of layer weights matrix.
Test for: wrong var type (not number) given in 1D array for weight initialization
Correct errors was caught. Error: Given input is not supported by implementation for weights initialization. Given values are not integers and thus can not represent of layer weights matrix.
Test for: wrong var type given (number, but no int) in 1D array for weight initialization
Correct errors was caught. Error: Given input is not supported by implementation for weight

FNN class implementation testing

In [37]:
#initialization by number of dim in vector
dim_layer = np.array([5,5,3,2,1])
testNet = FNN(dim_layer,identity,method_ini="Random")
print(testNet.weights_list[0])
print(testNet.weights_list[1])
print(testNet.weights_list[2])
print(testNet.weights_list[3])
print(testNet.activ_functions_list[0])
print(testNet.activ_functions_list[1])
print(testNet.activ_functions_list[2])
print(testNet.activ_functions_list[3])
#forward test pass
inputTestVect = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])

print(testNet.forward(inputTestVect))
print(testNet.forward(inputTestArray))


[[-0.63714809 -0.73392543 -0.01535404  0.17902251 -0.61209244 -0.0783883 ]
 [-0.49911025  0.37424343  0.43252964  0.44397739  0.51112557 -0.59471892]
 [-0.33478931  0.38055053 -0.44882977 -0.69722032  0.26978059  0.74719579]
 [ 0.38820814  0.72544925  0.4984846   0.09575951  0.60509861 -0.45976635]
 [-0.14857648 -0.50928417  0.16746759 -0.0994577  -0.44207178 -0.56924469]]
[[-0.76569876  0.59931611 -0.41566795  0.05623372  0.4210207  -0.05758078]
 [ 0.18245407  0.80641694  0.85204582  0.68374839  0.61261822 -0.05860781]
 [ 0.56933763 -0.5217913  -0.73851698 -0.47403047 -0.59245796 -0.190516  ]]
[[-0.10343311 -0.60003859 -0.68151337 -0.61293706]
 [-0.74181012  0.20437635 -0.82061213  0.18746547]]
[[-0.52445732 -1.00371325 -0.85736644]]
[<function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>, <function identity at 0x0000017F409949A0>]
[<function identity at 0x0000017F409949

In [38]:
#error messages testing
print("Test for: not supported input for weights")
try:
    dim_layer = "[5,5,3,2,1]"
    testNet = FNN(dim_layer,identity,method_ini="Random")
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error: ",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: array of not supported dimension")
try:
    dim_layer = np.array([[5,5,3,2,1],[5,5,3,2,1]])
    testNet = FNN(dim_layer,identity,method_ini="Random")
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedArrayDimGiven)):
        print("Correct errors was caught. Error: ",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: given numbers are not integers")
try:
    dim_layer = np.array([5,5,3.1,2,1])
    testNet = FNN(dim_layer,identity,method_ini="Random")
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error: ",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")
#
print("Test for: not enough numbers given. Minimally required input and output layers cannot be created")
try:
    dim_layer = np.array([5])
    testNet = FNN(dim_layer,identity,method_ini="Random")
except Exception as error_caught:
    if(isinstance(error_caught, NotSupportedInputGiven)):
        print("Correct errors was caught. Error: ",error_caught)
    else:
       print("Something went wrong: wrong error caught. Error: ", error_caught) 
else:
    print("Something went wrong: no error caught")

Test for: not supported input for weights
Correct errors was caught. Error:  Given input is not supported by implementation for weights initialization. 
Test for: array of not supported dimension
Correct errors was caught. Error:  Given array is of size not supported by implementation. Supported dimensions: 1.
Test for: given numbers are not integers
Correct errors was caught. Error:  Given input is not supported by implementation for weights initialization. Given values in vector must be integers to properly represent number of neurons in layers
Test for: not enough numbers given. Minimally required input and output layers cannot be created
Correct errors was caught. Error:  Given input is not supported by implementation for weights initialization. At least two numbers are needed for FNN creation: FNN needs at least input and output layer.


Reload Modules


In [39]:
import importlib
import sys
import numpy as np

# Reload order:
modules_in_order = [
    "ActivFunctions",
    "SuppFunctions",
    "InitFunctions",
    "Layer",
    "FNN",
    "TrainingFunctions"
]

for m in modules_in_order:
    if m in sys.modules:
        importlib.reload(sys.modules[m])
    else:
        globals()[m] = importlib.import_module(m)

print("All modules reloaded successfully.")


All modules reloaded successfully.


Imports

In [40]:
from FNN import FNN
from TrainingFunctions import backwards
from LossFunctions import MeanSquaredErrorDerivative

# Activations
from ActivFunctions import identity, sigmoid, tanh, relu, leaky_relu
import numpy as np


In [41]:
print("=== Test 1: Single-Layer Network Gradient ===")

dim_layer = np.array([4, 5])   # 4 inputs -> 5 outputs
testNet = FNN(dim_layer, identity, method_ini="Random")

inputTestVect = np.ones((4, 1))
targetVect = 0.5 * np.ones((5, 1))

grads = backwards(testNet, inputTestVect, targetVect, MeanSquaredErrorDerivative)

print("\nGradient matrix for single layer:")
print(grads[0])


=== Test 1: Single-Layer Network Gradient ===

Gradient matrix for single layer:
[[-0.28651963 -0.28651963 -0.28651963 -0.28651963 -0.28651963]
 [-0.20215458 -0.20215458 -0.20215458 -0.20215458 -0.20215458]
 [-0.04648601 -0.04648601 -0.04648601 -0.04648601 -0.04648601]
 [-0.10887373 -0.10887373 -0.10887373 -0.10887373 -0.10887373]
 [-0.25104898 -0.25104898 -0.25104898 -0.25104898 -0.25104898]]


In [42]:
print("=== Test 2: Deep 10-Layer Network ===")

dim_layer = np.array([
    5, 8, 6, 7, 5, 9, 4, 3, 2, 4, 1
])

deepNet = FNN(dim_layer, identity, method_ini="Random")

inputVect = np.ones((5, 1))
targetVect = np.array([[0.7]])

grads = backwards(deepNet, inputVect, targetVect, MeanSquaredErrorDerivative)

for i, g in enumerate(grads):
    print(f"\nGradient matrix for layer {i}:")
    print(g)


=== Test 2: Deep 10-Layer Network ===

Gradient matrix for layer 0:
[[ 0.07727597  0.07727597  0.07727597  0.07727597  0.07727597  0.07727597]
 [-0.14769014 -0.14769014 -0.14769014 -0.14769014 -0.14769014 -0.14769014]
 [ 0.17912042  0.17912042  0.17912042  0.17912042  0.17912042  0.17912042]
 [-0.21438547 -0.21438547 -0.21438547 -0.21438547 -0.21438547 -0.21438547]
 [-0.04274995 -0.04274995 -0.04274995 -0.04274995 -0.04274995 -0.04274995]
 [ 0.07400811  0.07400811  0.07400811  0.07400811  0.07400811  0.07400811]
 [-0.20884372 -0.20884372 -0.20884372 -0.20884372 -0.20884372 -0.20884372]
 [ 0.09958415  0.09958415  0.09958415  0.09958415  0.09958415  0.09958415]]

Gradient matrix for layer 1:
[[-0.27736981 -0.30991231  0.06742132  0.12852211 -0.14600172  0.18113258
  -0.0411052   0.37446738  0.15747543]
 [-0.01613784 -0.01803122  0.00392268  0.00747763 -0.00849462  0.0105386
  -0.00239157  0.02178714  0.00916218]
 [-0.20478568 -0.22881222  0.04977802  0.09488952 -0.10779493  0.1337325
  -