In [88]:
import numpy as np

from FNN import FNN
from Layer import Layer
from Neuron import Neuron

from ActivFunctions import *
from InitFunctions import *
from SuppFunctions import *

from LossFunctions import MeanSquaredError, MeanSquaredErrorDerivative
from TrainingFunctions import *



Neuron Class functionality testing

In [2]:
inputTest = np.array([1.0,1.0])

In [3]:
#zero initialization
t0NeuronZero = Neuron(2,identity)
print(t0NeuronZero.weight_vector.shape)
t0NeuronZero.forward(inputTest)

(1, 3)


[array([[0.]]), array([[0.]])]

In [4]:
#random initialization
t0NeuronRandom = Neuron(2,identity,method_ini="Random")
print(t0NeuronRandom.weight_vector.shape)
t0NeuronRandom.forward(inputTest)

(1, 3)


[array([[0.70627357]]), array([[0.70627357]])]

In [5]:
#initialization from vector
vector = np.array([1.0,2.0,3.5])
print(vector)
print(vector.shape)
t1Neuron = Neuron(vector,identity)
print(t1Neuron.weight_vector.shape)
t1Neuron.forward(inputTest)

[1.  2.  3.5]
(3,)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [6]:
#initialization from row vector(2D array)
vector_row = vector[np.newaxis,:]
print(vector_row)
print(vector_row.shape)
t2Neuron = Neuron(vector_row,identity)
print(t2Neuron.weight_vector.shape)
t2Neuron.forward(inputTest)

[[1.  2.  3.5]]
(1, 3)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [7]:
#initialization from column vector(2D array)
vector_column = vector[:,np.newaxis]
print(vector_column)
print(vector_column.shape)
t3Neuron = Neuron(vector_column,identity)
print(t3Neuron.weight_vector.shape)
t3Neuron.forward(inputTest)

[[1. ]
 [2. ]
 [3.5]]
(3, 1)
(1, 3)


[array([[6.5]]), array([[6.5]])]

In [8]:
#array input
t0NeuronRandom = Neuron(2,identity,method_ini="Random")
inputTest = np.array([[1.0,1.0],[1.0,1.0]])
print(inputTest.shape)
print(inputTest)
print(t0NeuronRandom.weight_vector.shape)
t0NeuronRandom.forward(inputTest)

(2, 2)
[[1. 1.]
 [1. 1.]]
(1, 3)


[array([[0.62823325, 0.62823325]]), array([[0.62823325, 0.62823325]])]

In [9]:
#wrong activ function
vector = np.array([1.0,2.0,3.5])
errorNeuron = Neuron(vector,1)

NotImplementedError: 

In [ ]:
#wrong input function
vector = np.array(["1.0","2.0","3.5"])
errorNeuron = Neuron(vector,identity)

NotImplementedError: 

In [ ]:
#wrong input (too small)
vector = np.array([1.0,2.0,3.5])
neuronTest = Neuron(vector,identity)
inputTestErrorSmall = np.array([1.0])
neuronTest.forward(inputTestErrorSmall)

NotImplementedError: 

In [ ]:
#wrong input (too big)
vector = np.array([1.0,2.0,3.5])
neuronTest = Neuron(vector,identity)
inputTestErrorBig = np.array([[1.0],[1.0],[1.0],[1.0]])
print(inputTestErrorBig)
neuronTest.forward(inputTestErrorBig)

[[1.]
 [1.]
 [1.]
 [1.]]


NotImplementedError: 

Layer class implementation testing

In [ ]:
#initialization by number of dim in vector
dim_layer = np.array([4,5])
testLayer = Layer(dim_layer,identity,method_ini="Random")
testLayer.weights_array
testLayer.activ_functions

[<function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>,
 <function ActivFunctions.identity(x)>]

In [ ]:
#forward test pass
inputTestVect = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])

print(testLayer.forward(inputTestVect))
print(testLayer.forward(inputTestArray))

[array([[2.93741261],
       [3.16570166],
       [4.12556719],
       [3.06488001]]), array([[2.93741261],
       [3.16570166],
       [4.12556719],
       [3.06488001]])]
[array([[2.93741261, 4.92025167],
       [3.16570166, 6.10149423],
       [4.12556719, 7.70806968],
       [3.06488001, 5.19384362]]), array([[2.93741261, 4.92025167],
       [3.16570166, 6.10149423],
       [4.12556719, 7.70806968],
       [3.06488001, 5.19384362]])]


FNN class implementation testing

In [48]:
#initialization by number of dim in vector
dim_layer = np.array([5,5,3,2,1])
testNet = FNN(dim_layer,identity,method_ini="Random")
print(testNet.weights_list[0])
print(testNet.weights_list[1])
print(testNet.weights_list[2])
print(testNet.weights_list[3])
print(testNet.activ_functions_list[0])
print(testNet.activ_functions_list[1])
print(testNet.activ_functions_list[2])
print(testNet.activ_functions_list[3])
#forward test pass
inputTestVect = np.array([[1.0],[1.0],[1.0],[1.0],[1.0]])
inputTestArray = np.array([[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0],[1.0,2.0]])

print(testNet.forward(inputTestVect))
print(testNet.forward(inputTestArray))


[[ 0.61626292  0.19959915  0.62172801 -0.63974596 -0.26070004 -0.50077126]
 [-0.14623161  0.6963198   0.24438238  0.42812175  0.13016267 -0.75848825]
 [ 0.66673259  0.01408218  0.64503096 -0.75380741 -0.34503707  0.11295241]
 [-0.69215898  0.39412309 -0.16111514 -0.38307233 -0.27956107  0.63618899]
 [-0.16017978 -0.26503363 -0.40585878  0.00746522  0.62278534 -0.22186549]]
[[-0.20610323 -0.69273396  0.20371347  0.2155034  -0.09319704  0.1441488 ]
 [-0.16161647 -0.227738   -0.8081017   0.22360254  0.00646229 -0.2445102 ]
 [-0.66248951 -0.45177534 -0.5005022   0.08242032 -0.16558165 -0.11743244]]
[[ 0.64200819 -0.62464916  0.13342353 -0.92913895]
 [-0.05628612 -0.33774619  0.59364401  0.59003193]]
[[ 0.14267573 -0.50245973  1.19914026]]
[<function identity at 0x000002787F7FCAE0>, <function identity at 0x000002787F7FCAE0>, <function identity at 0x000002787F7FCAE0>, <function identity at 0x000002787F7FCAE0>, <function identity at 0x000002787F7FCAE0>]
[<function identity at 0x000002787F7FCA

In [82]:
import importlib
import sys
import numpy as np

# Reload order:
# ActivFunctions → SuppFunctions → InitFunctions → Layer → FNN → TrainingFunctions

modules_in_order = [
    "ActivFunctions",
    "SuppFunctions",
    "InitFunctions",
    "Layer",
    "FNN",
    "TrainingFunctions"
]

for m in modules_in_order:
    if m in sys.modules:
        importlib.reload(sys.modules[m])
    else:
        globals()[m] = importlib.import_module(m)

print("All modules reloaded successfully.")


All modules reloaded successfully.


In [83]:
from FNN import FNN
from TrainingFunctions import backwards
from LossFunctions import MeanSquaredErrorDerivative

# Activations
from ActivFunctions import identity, sigmoid, tanh, relu, leaky_relu


In [84]:
print("=== Test 1: Single-Layer Network Gradient ===")

dim_layer = np.array([4, 5])   # 4 inputs -> 5 outputs
testNet = FNN(dim_layer, identity, method_ini="Random")

inputTestVect = np.ones((4, 1))
targetVect = 0.5 * np.ones((5, 1))

grads = backwards(testNet, inputTestVect, targetVect, MeanSquaredErrorDerivative)

print("\nGradient matrix for single layer:")
print(grads[0])


=== Test 1: Single-Layer Network Gradient ===

Gradient matrix for single layer:
[[-0.16276989 -0.16276989 -0.16276989 -0.16276989 -0.16276989]
 [-0.24629254 -0.24629254 -0.24629254 -0.24629254 -0.24629254]
 [ 0.13981264  0.13981264  0.13981264  0.13981264  0.13981264]
 [ 0.00959806  0.00959806  0.00959806  0.00959806  0.00959806]
 [-0.30529699 -0.30529699 -0.30529699 -0.30529699 -0.30529699]]


In [85]:
print("=== Test 2: Deep 10-Layer Network ===")

dim_layer = np.array([
    5,   # input size
    8,
    6,
    7,
    5,
    9,
    4,
    3,
    2,
    4,
    1    # output
])

deepNet = FNN(dim_layer, identity, method_ini="Random")

inputVect = np.ones((5, 1))
targetVect = np.array([[0.7]])

grads = backwards(deepNet, inputVect, targetVect, MeanSquaredErrorDerivative)

for i, g in enumerate(grads):
    print(f"\nGradient matrix for layer {i}:")
    print(g)


=== Test 2: Deep 10-Layer Network ===

Gradient matrix for layer 0:
[[ 0.05805558  0.05805558  0.05805558  0.05805558  0.05805558  0.05805558]
 [-0.05226774 -0.05226774 -0.05226774 -0.05226774 -0.05226774 -0.05226774]
 [ 0.24074708  0.24074708  0.24074708  0.24074708  0.24074708  0.24074708]
 [ 0.07350435  0.07350435  0.07350435  0.07350435  0.07350435  0.07350435]
 [ 0.13830191  0.13830191  0.13830191  0.13830191  0.13830191  0.13830191]
 [ 0.25552996  0.25552996  0.25552996  0.25552996  0.25552996  0.25552996]
 [ 0.00082988  0.00082988  0.00082988  0.00082988  0.00082988  0.00082988]
 [-0.11304242 -0.11304242 -0.11304242 -0.11304242 -0.11304242 -0.11304242]]

Gradient matrix for layer 1:
[[-0.03632896 -0.00800155  0.04161969 -0.02740295 -0.02959799  0.02512628
   0.00938123  0.00599952  0.00602289]
 [-0.29777426 -0.06558553  0.3411403  -0.22461125 -0.24260311  0.20595027
   0.07689425  0.04917573  0.04936726]
 [-0.1373939  -0.03026135  0.15740312 -0.10363628 -0.11193777  0.09502605
 

In [86]:
print("=== Test 3: Activation Function Sanity ===")

activations = [identity, sigmoid, tanh, relu, leaky_relu]
x = np.linspace(-3, 3, 7).reshape(-1,1)

for act in activations:
    out = act(x)
    print(f"\nActivation: {act.__name__}")
    print("Input:\n", x.T)
    print("Output:\n", out.T)


=== Test 3: Activation Function Sanity ===

Activation: identity
Input:
 [[-3. -2. -1.  0.  1.  2.  3.]]
Output:
 [[-3. -2. -1.  0.  1.  2.  3.]]

Activation: sigmoid
Input:
 [[-3. -2. -1.  0.  1.  2.  3.]]
Output:
 [[0.04742587 0.11920292 0.26894142 0.5        0.73105858 0.88079708
  0.95257413]]

Activation: tanh
Input:
 [[-3. -2. -1.  0.  1.  2.  3.]]
Output:
 [[-0.99505475 -0.96402758 -0.76159416  0.          0.76159416  0.96402758
   0.99505475]]

Activation: relu
Input:
 [[-3. -2. -1.  0.  1.  2.  3.]]
Output:
 [[0. 0. 0. 0. 1. 2. 3.]]

Activation: leaky_relu
Input:
 [[-3. -2. -1.  0.  1.  2.  3.]]
Output:
 [[-0.03 -0.02 -0.01  0.    1.    2.    3.  ]]


In [87]:
print("=== Test 4: Backprop With ReLU Hidden Layers ===")

dim_layer = np.array([3, 4, 2])   # Small net
testNet = FNN(dim_layer, relu, method_ini="Random")

inputVect = np.ones((3, 1))
targetVect = np.array([[0.2], [0.8]])

grads = backwards(testNet, inputVect, targetVect, MeanSquaredErrorDerivative)

for i, g in enumerate(grads):
    print(f"\nReLU Net - Gradient for layer {i}:")
    print(g)


=== Test 4: Backprop With ReLU Hidden Layers ===

ReLU Net - Gradient for layer 0:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

ReLU Net - Gradient for layer 1:
[[ 0.46768105  0.          0.          0.          0.        ]
 [-0.73621247  0.          0.          0.          0.        ]]


In [88]:
print("=== Test 5: Randomized Gradient Stability ===")

for run in range(3):
    dim_layer = np.array([4, 6, 5, 3])
    net = FNN(dim_layer, tanh, method_ini="Random")

    x = np.random.randn(4, 1)
    y = np.random.randn(3, 1)

    grads = backwards(net, x, y, MeanSquaredErrorDerivative)
    
    print(f"\nRun {run+1} — Max gradient magnitude across layers:")
    for i, g in enumerate(grads):
        print(f"  Layer {i}: {np.max(np.abs(g)):.4f}")


=== Test 5: Randomized Gradient Stability ===

Run 1 — Max gradient magnitude across layers:
  Layer 0: 0.4226
  Layer 1: 0.4800
  Layer 2: 0.6118

Run 2 — Max gradient magnitude across layers:
  Layer 0: 0.4671
  Layer 1: 0.4507
  Layer 2: 0.4800

Run 3 — Max gradient magnitude across layers:
  Layer 0: 0.5554
  Layer 1: 0.4653
  Layer 2: 0.4796


In [89]:
print("=== Test 6: Numerical Gradient Check (Finite Difference) ===")

eps = 1e-5

dim_layer = np.array([3, 4, 2])
net = FNN(dim_layer, sigmoid, method_ini="Random")

x = np.random.randn(3, 1)
y = np.random.randn(2, 1)

# Analytical gradients
grads_analytical = backwards(net, x, y, MeanSquaredErrorDerivative)

# Numeric gradient for layer 0
W = net.weights_list[0]
num_grad = np.zeros_like(W)

for i in range(W.shape[0]):
    for j in range(W.shape[1]):
        orig = W[i, j]

        W[i, j] = orig + eps
        plus = net.forward(x)[1][-1]
        L_plus = 0.5 * np.sum((plus - y) ** 2)

        W[i, j] = orig - eps
        minus = net.forward(x)[1][-1]
        L_minus = 0.5 * np.sum((minus - y) ** 2)

        num_grad[i, j] = (L_plus - L_minus) / (2 * eps)
        W[i, j] = orig  # restore

print("\nAnalytical vs Numerical (Layer 0):")
print("Analytical:\n", grads_analytical[0])
print("Numerical:\n", num_grad)


=== Test 6: Numerical Gradient Check (Finite Difference) ===

Analytical vs Numerical (Layer 0):
Analytical:
 [[ 0.00485345  0.00329078 -0.00527327  0.00369963]
 [-0.00454649 -0.00308265  0.00493975 -0.00346564]
 [ 0.01407563  0.00954369 -0.01529316  0.01072942]
 [ 0.00204839  0.00138887 -0.00222558  0.00156143]]
Numerical:
 [[ 0.00485345  0.00329078 -0.00527327  0.00369963]
 [-0.00454649 -0.00308265  0.00493975 -0.00346564]
 [ 0.01407563  0.00954369 -0.01529316  0.01072942]
 [ 0.00204839  0.00138887 -0.00222558  0.00156143]]
